# Generated by Django 5.0 on 2023-12-19 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 15, 11, 53, 267411, tzinfo=datetime.timezone.utc)),
        ),
    ]
